# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sha1.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sha1.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\nsha1.proto\".\n\x08\x46ileData\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x10\n\x08sha1_val\x18\x02 \x01(\t\"G\n\x06Result\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x14\n\x0c\x63orrect_sha1\x18\x02 \x01(\t\x12\x17\n\x0f\x63\x61lculated_sha1\x18\x03 \x01(\t20\n\x0bSha1Checker\x12!\n\tCheckSha1\x12\t.FileData\x1a\x07.Result\"\x00\x62\x06proto3'
)




_FILEDATA = _descriptor.Descriptor(
  name='FileData',
  full_name='FileData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='FileData.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sha1_val', full_name='FileData.sha1_val', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=60,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='Result.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='correct_sha1', full_name='Result.correct_sha1', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='calculated_sha1', full_name='Result.calculated_sha1', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=133,
)

DESCRIPTOR.message_types_by_name['FileData'] = _FILEDATA
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileData = _reflection.GeneratedProtocolMessageType('FileData', (_message.Message,), {
  'DESCRIPTOR' : _FILEDATA,
  '__module__' : 'sha1_pb2'
  # @@protoc_insertion_point(class_scope:FileData)
  })
_sym_db.RegisterMessage(FileData)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'sha1_pb2'
  # @@protoc_insertion_point(class_scope:Result)
  })
_sym_db.RegisterMessage(Result)



_SHA1CHECKER = _descriptor.ServiceDescriptor(
  name='Sha1Checker',
  full_name='Sha1Checker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=135,
  serialized_end=183,
  methods=[
  _descriptor.MethodDescriptor(
    name='CheckSha1',
    full_name='Sha1Checker.CheckSha1',
    index=0,
    containing_service=None,
    input_type=_FILEDATA,
    output_type=_RESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SHA1CHECKER)

DESCRIPTOR.services_by_name['Sha1Checker'] = _SHA1CHECKER

# @@protoc_insertion_point(module_scope)
